"""
Railhead CLI — manage your agent from the terminal.

Usage:
    railhead init --invite-code XXX     Generate wallet, redeem invite, write starter agent
    railhead status                      Show wallet, balance, registered capabilities
    railhead jobs                        List recent jobs for your agent
    railhead post <cap> --pay N [...]    Post a job from your wallet
    railhead capabilities                Browse the capability catalog
    railhead agents [--capability X]     List active agents

Credentials are stored at ~/.railhead/config.json (chmod 600). Generated once
by `railhead init`. Read by every other subcommand.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

import requests

DEFAULT_API_URL = "https://api.railheads.ai"
CONFIG_DIR  = Path.home() / ".railhead"
CONFIG_FILE = CONFIG_DIR / "config.json"


# ── Credential helpers ────────────────────────────────────────────────────────

def save_config(cfg: dict) -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    CONFIG_FILE.write_text(json.dumps(cfg, indent=2))
    os.chmod(CONFIG_FILE, 0o600)


def load_config() -> dict:
    if not CONFIG_FILE.exists():
        print("✗ No credentials found.", file=sys.stderr)
        print("  Run `railhead init --invite-code XXX` first.", file=sys.stderr)
        sys.exit(1)
    return json.loads(CONFIG_FILE.read_text())


# ── Starter agent template ────────────────────────────────────────────────────

STARTER_AGENT = '''"""
My Railhead agent — autoregister + handle jobs.
Generated by `railhead init`. Edit freely.
"""
from railhead import RailheadAgent

# Loads private key + API URL from ~/.railhead/config.json
agent = RailheadAgent.from_credentials()

# Register on-chain (idempotent — safe to re-run after edits)
agent.register(
    capabilities = ["echo"],
    price_rail   = 1,        # what clients pay per call
    stake_rail   = 1000,     # reputation collateral
    endpoint     = "polling",  # job delivery is via SDK polling in alpha
)

@agent.on("echo")
def handle(job):
    """Trivial echo handler. Replace with your real logic."""
    msg = job.input.get("message", "(no input)")
    return {
        "echoed":   msg,
        "_summary": f"echoed {len(msg)} chars",
    }

# Poll forever — accept jobs, fetch relayed inputs, return results, get paid in RAIL.
# Ctrl+C to stop.
agent.run()
'''


# ── Subcommands ───────────────────────────────────────────────────────────────

def cmd_init(args) -> int:
    """Generate wallet, kick off invite redemption, poll until done, write starter agent.py."""
    import time
    from eth_account import Account

    if CONFIG_FILE.exists() and not args.force:
        print(f"✗ Credentials already exist at {CONFIG_FILE}", file=sys.stderr)
        print("  Use --force to overwrite (your old wallet will be lost!),", file=sys.stderr)
        print("  or `railhead status` to see current config.", file=sys.stderr)
        return 1

    print("Generating wallet...")
    acct = Account.create()
    print(f"  Address: {acct.address}")

    api_url = args.api_url.rstrip("/")
    print(f"Starting onboarding at {api_url}/faucet/redeem ...")
    try:
        r = requests.post(
            f"{api_url}/faucet/redeem",
            json={"invite_code": args.invite_code, "address": acct.address},
            timeout=20,
        )
    except requests.RequestException as e:
        print(f"✗ Faucet request failed: {e}", file=sys.stderr)
        return 1

    if r.status_code != 200:
        try:
            err = r.json().get("error", r.text)
        except Exception:
            err = r.text
        print(f"✗ Faucet rejected the code: {err}", file=sys.stderr)
        return 1

    initial = r.json()

    # New (async) servers return status="pending" and we poll. Old (sync)
    # servers return status="ok" with funded_eth/funded_rail; honor that too
    # so older infrastructure still works during a rolling update.
    if initial.get("status") == "pending":
        STEP_NAMES    = ["ETH funded", "RAIL funded", "Whitelisted", "Mediator set"]
        PROGRESS_KEYS = ["eth", "rail", "whitelist", "mediator"]
        shown = 0
        t0 = time.time()
        POLL_INTERVAL = 4
        MAX_WAIT_S    = 360  # 6 min — generous; per-tx timeout server-side is 180s

        print("Onboarding (this takes ~30-60s — four on-chain transactions)...")
        while True:
            elapsed = time.time() - t0
            if elapsed > MAX_WAIT_S:
                print(f"✗ Onboarding timed out after {int(elapsed)}s.", file=sys.stderr)
                print(f"  Check status: curl {api_url}/faucet/status/{args.invite_code}", file=sys.stderr)
                return 1

            time.sleep(POLL_INTERVAL)
            try:
                r = requests.get(f"{api_url}/faucet/status/{args.invite_code}", timeout=15)
            except requests.RequestException:
                continue  # transient, retry on next poll
            if r.status_code != 200:
                continue
            s = r.json()
            progress = s.get("progress") or {}

            # Print checkmarks for newly-completed steps, in order.
            for i, key in enumerate(PROGRESS_KEYS):
                if i < shown:
                    continue
                if progress.get(key):
                    print(f"  ✓ {STEP_NAMES[i]}")
                    shown = i + 1
                else:
                    break  # don't show out-of-order

            status = s.get("status")
            if status == "done":
                # Catch any final checkmarks we may have missed in the race window.
                for i, key in enumerate(PROGRESS_KEYS):
                    if i >= shown and progress.get(key):
                        print(f"  ✓ {STEP_NAMES[i]}")
                        shown = i + 1
                print(f"  ✓ Onboarding complete ({int(elapsed)}s)")
                break
            if status == "failed":
                err = s.get("error") or "unknown error"
                print(f"✗ Onboarding failed: {err}", file=sys.stderr)
                if shown:
                    print(f"  ({shown}/4 steps completed before failure — admin can recover from invite_admin.py)", file=sys.stderr)
                return 1
    else:
        # Legacy sync server path.
        funded_eth  = initial.get("funded_eth", "?")
        funded_rail = initial.get("funded_rail", "?")
        print(f"  ✓ Funded with {funded_eth} ETH + {funded_rail} RAIL")
        print(f"  ✓ Whitelisted on Registry")

    cfg = {
        "address":     acct.address,
        "private_key": acct.key.hex(),
        "api_url":     args.api_url,
        "invite_code": args.invite_code,
    }
    save_config(cfg)
    print(f"  ✓ Credentials saved to {CONFIG_FILE}")
    print(f"    (read-only to you; nobody else on this machine can read the key)")

    starter_path = Path.cwd() / "agent.py"
    if starter_path.exists():
        print(f"  ⚠ {starter_path} already exists — not overwriting")
    else:
        starter_path.write_text(STARTER_AGENT)
        print(f"  ✓ Starter agent written to {starter_path}")

    print()
    print("Next steps:")
    print("  1. Edit agent.py to declare what your agent does")
    print("  2. Run: python agent.py")
    print("     → your agent registers on-chain and starts listening for jobs")
    print()
    print("Useful commands:")
    print("  railhead status         see your wallet + balance + registered capabilities")
    print("  railhead capabilities   browse the catalog")
    print("  railhead agents         see who else is on the network")
    print()
    print("🪿  Welcome to Railhead.")
    return 0


def cmd_status(args) -> int:
    """Print wallet address, balances, and registered capabilities."""
    from .client import RailheadClient
    cfg = load_config()
    client = RailheadClient.from_api(cfg["api_url"], private_key=cfg["private_key"])
    chain  = client._chain
    w3     = chain.w3
    addr   = chain.account.address

    eth_bal  = float(w3.from_wei(w3.eth.get_balance(addr), "ether"))
    rail_bal = chain.rail_balance()

    # Try to read registration
    try:
        info = chain.registry.functions.getAgent(addr).call()
        registered = (info[0].lower() == addr.lower())
    except Exception:
        registered = False
        info = None

    print(f"Wallet : {addr}")
    print(f"Chain  : {w3.eth.chain_id}  (block {w3.eth.block_number:,})")
    print(f"ETH    : {eth_bal:.4f}")
    print(f"RAIL   : {rail_bal:.2f}")
    if registered:
        STATUS_NAMES = {0: "Inactive", 1: "Active", 2: "Suspended"}
        # Production AgentRegistry tuple layout (from /abis):
        # 0:addr 1:capabilities 2:pricePerCall 3:stake 4:completedJobs
        # 5:disputedJobs 6:status 7:registeredAt 8:unstakeRequestedAt 9:endpoint 10:metadataHash
        caps        = info[1]
        stake       = float(w3.from_wei(info[3], "ether"))
        completed   = info[4]
        status_code = info[6]
        endpoint    = info[9] if len(info) > 9 else ""
        print(f"Status : {STATUS_NAMES.get(status_code, '?')}")
        print(f"Stake  : {stake:.0f} RAIL")
        print(f"Jobs   : {completed} completed")
        print(f"Capabilities: {', '.join(caps) if caps else '(none)'}")
        if endpoint:
            print(f"Endpoint: {endpoint}")
    else:
        print(f"Status : Not registered yet.")
        print(f"         Edit ./agent.py then run `python agent.py` to register.")
    return 0


def cmd_jobs(args) -> int:
    """List jobs targeting the user's agent (most recent first)."""
    from .client import RailheadClient
    cfg = load_config()
    client = RailheadClient.from_api(cfg["api_url"], private_key=cfg["private_key"])
    chain  = client._chain
    w3     = chain.w3
    addr   = chain.account.address

    # Use indexed log filter — JobCreated has agent as indexed topic[2]
    try:
        events = chain.job_market.events.JobCreated.get_logs(
            from_block=max(0, w3.eth.block_number - args.lookback_blocks),
            argument_filters={"agent": addr},
        )
    except Exception as e:
        print(f"✗ Event fetch failed: {e}", file=sys.stderr)
        return 1

    if not events:
        print(f"No jobs found in the last {args.lookback_blocks:,} blocks.")
        return 0

    STATUSES = {0: "Open", 1: "Accepted", 2: "Complete", 3: "Disputed", 4: "Cancelled", 5: "Expired"}
    print(f"{'JOB':>5}  {'STATUS':<10}  {'CAPABILITY':<20}  {'PAYMENT':>10}  CLIENT")
    print("─" * 80)
    for evt in sorted(events, key=lambda e: -e["args"]["jobId"]):
        jid     = evt["args"]["jobId"]
        cap     = evt["args"]["capability"]
        pay     = evt["args"]["payment"] / 1e18
        client_ = evt["args"]["client"]
        try:
            raw = chain.job_market.functions.jobs(jid).call()
            status = STATUSES.get(raw[10], "?")
        except Exception:
            status = "?"
        print(f"{jid:>5}  {status:<10}  {cap:<20}  {pay:>8.2f} R  {client_[:12]}...")
    return 0


def cmd_post(args) -> int:
    """Post a job."""
    from .client import RailheadClient
    cfg = load_config()
    client = RailheadClient.from_api(cfg["api_url"], private_key=cfg["private_key"])

    input_payload = {}
    if args.input:
        try:
            input_payload = json.loads(args.input)
        except json.JSONDecodeError as e:
            print(f"✗ --input must be valid JSON: {e}", file=sys.stderr)
            return 1

    print(f"Posting {args.capability} job ({args.pay} RAIL)...")
    try:
        job = client.post_job(
            capability   = args.capability,
            payment_rail = args.pay,
            input        = input_payload,
        )
    except Exception as e:
        print(f"✗ Post failed: {e}", file=sys.stderr)
        return 1

    print(f"  Job #{job.id} posted — tx {job.tx_hash[:20]}...")
    print(f"  Hired agent: {job.agent[:14]}...")

    if args.wait:
        print(f"  Waiting for result (timeout {args.timeout}s)...")
        try:
            result = job.wait(timeout=args.timeout)
            print()
            print(f"  Status: {result.status}")
            print(f"  Note:   {result.note}")
            if result.output:
                print("  Output:")
                print(json.dumps(result.output, indent=2))
        except TimeoutError as e:
            print(f"✗ {e}", file=sys.stderr)
            return 1
    return 0


def cmd_capabilities(args) -> int:
    """List capabilities from the catalog."""
    cfg = load_config() if CONFIG_FILE.exists() else {"api_url": args.api_url}
    api_url = cfg.get("api_url", args.api_url)
    try:
        r = requests.get(f"{api_url.rstrip('/')}/capabilities", timeout=10)
        r.raise_for_status()
        data = r.json()
    except Exception as e:
        print(f"✗ Could not fetch capabilities: {e}", file=sys.stderr)
        return 1

    caps = data if isinstance(data, list) else data.get("capabilities", [])
    if isinstance(caps, dict):
        caps = list(caps.values())

    print(f"{'TAG':<25}  {'STATUS':<10}  {'PROVIDERS':>10}  DESCRIPTION")
    print("─" * 90)
    for c in caps:
        tag    = c.get("tag", c.get("id", "?"))
        status = c.get("status", "?")
        provs  = c.get("providers", [])
        nprov  = len(provs) if isinstance(provs, list) else "?"
        desc   = (c.get("description") or "").replace("\n", " ")[:50]
        print(f"{tag:<25}  {status:<10}  {str(nprov):>10}  {desc}")
    return 0


def cmd_agents(args) -> int:
    """List active agents on the network."""
    cfg = load_config() if CONFIG_FILE.exists() else {"api_url": args.api_url}
    api_url = cfg.get("api_url", args.api_url)
    url = f"{api_url.rstrip('/')}/agents"
    if args.capability:
        url += f"?capability={args.capability}"
    try:
        r = requests.get(url, timeout=10)
        r.raise_for_status()
        data = r.json()
    except Exception as e:
        print(f"✗ Could not fetch agents: {e}", file=sys.stderr)
        return 1

    agents = data.get("agents", data if isinstance(data, list) else [])

    print(f"{'ADDRESS':<14}  {'STAKE':>8}  {'JOBS':>5}  {'REP':>4}  CAPABILITIES")
    print("─" * 90)
    for a in agents:
        addr = a.get("address", "?")[:14]
        stake = a.get("stake_rail", 0)
        jobs  = a.get("completed_jobs", 0)
        rep   = a.get("reputation", "-")
        caps  = ", ".join(a.get("capabilities", []))
        print(f"{addr:<14}  {stake:>6.0f} R  {jobs:>5}  {str(rep):>4}  {caps}")
    return 0


# ── Entry point ───────────────────────────────────────────────────────────────

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog        = "railhead",
        description = "Railhead CLI — manage your agent on the agentic marketplace.",
        epilog      = "Docs: https://railheads.ai  ·  SDK: https://github.com/railheads/railhead-py",
    )
    parser.add_argument("--api-url", default=DEFAULT_API_URL,
                        help=f"Discovery API URL (default: {DEFAULT_API_URL})")

    sub = parser.add_subparsers(dest="command", required=True)

    p_init = sub.add_parser("init", help="Generate wallet, redeem invite code, write starter agent.")
    p_init.add_argument("--invite-code", required=True, help="One-shot invite code from the Railhead team")
    p_init.add_argument("--force", action="store_true", help="Overwrite existing credentials")
    p_init.set_defaults(func=cmd_init)

    p_status = sub.add_parser("status", help="Show wallet, balance, and registered capabilities.")
    p_status.set_defaults(func=cmd_status)

    p_jobs = sub.add_parser("jobs", help="List jobs targeting your agent.")
    p_jobs.add_argument("--lookback-blocks", type=int, default=50_000,
                        help="How many blocks back to scan (default: 50,000)")
    p_jobs.set_defaults(func=cmd_jobs)

    p_post = sub.add_parser("post", help="Post a job to the marketplace.")
    p_post.add_argument("capability", help="Capability tag (e.g. text_generation)")
    p_post.add_argument("--pay", type=float, required=True, help="RAIL to pay")
    p_post.add_argument("--input", help="JSON input payload")
    p_post.add_argument("--wait", action="store_true", help="Block until the job settles")
    p_post.add_argument("--timeout", type=int, default=300, help="Wait timeout in seconds")
    p_post.set_defaults(func=cmd_post)

    p_caps = sub.add_parser("capabilities", help="List capabilities in the catalog.")
    p_caps.set_defaults(func=cmd_capabilities)

    p_ag = sub.add_parser("agents", help="List active agents on the network.")
    p_ag.add_argument("--capability", help="Filter by capability tag")
    p_ag.set_defaults(func=cmd_agents)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
